package com.astro5star.app.utils

object Localization {
    // English Strings
    private val english = mapOf(
        "home_title" to "Astro 5 Star",
        "home" to "Home",
        "profile" to "Profile",
        "settings" to "Settings",
        "logout" to "Logout",
        "join_as_astrologer" to "Join as Astrologer",
        "name" to "Full Name",
        "phone_number" to "Phone Number",
        "email_address" to "Email Address",
        "experience_years" to "Experience (Years)",
        "skills_expert" to "Skills (e.g. Vedic, Tarot)",
        "price_per_min" to "Price Per Min",
        "about_you" to "About You",
        "register_now" to "Register Now",
        "premium_consultation" to "Premium Consultation",
        "vedic_remedies" to "Vedic Remedies",
        "gemstone_guide" to "Gemstone Guide",
        "horoscope" to "Horoscope",
        "live_astrologer" to "Live Astrologer",
        "daily_horoscope" to "Daily Horoscope",
        "chat_services" to "Chat Services",
        "video_call" to "Video Call",
        "audio_call" to "Audio Call",
        "view_all" to "View All",
        "loading" to "Loading...",
        "aries" to "Aries",
        "taurus" to "Taurus",
        "gemini" to "Gemini",
        "cancer" to "Cancer",
        "leo" to "Leo",
        "virgo" to "Virgo",
        "libra" to "Libra",
        "scorpio" to "Scorpio",
        "sagittarius" to "Sagittarius",
        "capricorn" to "Capricorn",
        "aquarius" to "Aquarius",
        "pisces" to "Pisces",
        "all" to "All",
        "love" to "Love",
        "career" to "Career",
        "finance" to "Finance",
        "marriage" to "Marriage",
        "health" to "Health",
        "education" to "Education",
        "element" to "Element",
        "lord" to "Lord",
        "category" to "Category",
        "daily_prediction" to "Daily Prediction",
        "ok" to "OK",
        "real_name" to "Real Name *",
        "display_name" to "Display Name (For App)",
        "gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "dob" to "Date of Birth",
        "tob" to "Time of Birth",
        "pob" to "Place of Birth",
        "cell_no_1" to "Cell Number 1 *",
        "cell_no_2" to "Cell Number 2",
        "whatsapp_no" to "WhatsApp Number",
        "address" to "Full Address",
        "aadhar_no" to "Aadhar Number",
        "pan_no" to "PAN Number",
        "profession" to "Profession (e.g. Vedic, Tarot)",
        "bank_details" to "Bank Details (Acct No / IFSC)",
        "upi_name" to "UPI Name",
        "upi_number" to "UPI Number",
        "submit_registration" to "Submit Registration",
        "personal_details" to "Personal Details",
        "birth_details" to "Birth Details",
        "contact_info" to "Contact Info",
        "professional_info" to "Professional Info",
        "payment_details" to "Payment Details",
        "consultation_history" to "Consultation History",
        "unlimited_horoscope" to "Unlimited Horoscope (40 Min)",
        "unlimited_horoscope_desc" to "Get in-depth guidance on love, career, health, wealth & more.",
        "chat" to "Chat",
        "video" to "Video",
        "call" to "Call",
        "joined_queue" to "Joined Queue! You'll be notified.",
        "failed_join_queue" to "Failed to join queue",
        "low_balance_title" to "Low Balance!",
        "low_balance_desc" to "Current session ended due to insufficient funds. Please recharge to continue.",
        "add_funds_now" to "Add Funds Now",
        "later" to "I'll do it later",
        "emergency_banner_title" to "Online for Emergency!",
        "emergency_banner_desc" to "Boost your earnings with emergency sessions.",
        "total_earnings" to "Total Earnings",
        "withdraw" to "Withdraw",
        "min_withdrawal_desc" to "Min. ₹500 required",
        "withdrawal_request_success" to "Withdrawal Requested Successfully",
        "withdrawal_history_title" to "Recent Withdrawal Status",
        "today_progress" to "Today's Progress",
        "service_availability" to "Service Availability",
        "customers_waiting" to "customers waiting",
        "process_current_session" to "Process your current session to connect with the next person.",
        "earnings" to "Earnings",
        "history" to "History",
        "unlimited_session" to "session",
        "press_back_again_to_end" to "Press back again to end the call",
        "muted" to "Muted",
        "unmuted" to "Unmuted",
        "camera_on" to "Camera ON",
        "camera_off" to "Camera OFF",
        "speaker_on" to "Speaker ON",
        "speaker_off" to "Speaker OFF",
        "waiting_client_data" to "Waiting for Client Data...",
        "details_updated" to "Details Updated",
        "failed_calculate_match" to "Failed to calculate match",
        "error_calculate_match" to "Error calculating match",
        "recording_started" to "Recording started",
        "recording_failed" to "Recording failed",
        "recording_synced" to "Recording synced to cloud",
        "review_dialog_title" to "How was your session?",
        "review_placeholder" to "Share your experience (optional)",
        "submit_review" to "Submit Review",
        "skip" to "Skip",
        "review_submitted" to "Review submitted!",
        "communication_established" to "Communication Established",
        "consultation_started" to "Consultation Started",
        "view_rasi_chart" to "View Chart",
        "client_rasi_chart" to "Client Rasi Chart",
        "partner_rasi_chart" to "Partner Rasi Chart",
        "marriage_compatibility" to "Marriage Compatibility Match"
    )

    // Tamil Strings
    private val tamil = mapOf(
        "home_title" to "ஆஸ்ட்ரோ 5 ஸ்டார்",
        "home" to "முகப்பு",
        "profile" to "சுயவிவரம்",
        "settings" to "அமைப்புகள்",
        "logout" to "வெளியேறு",
        "join_as_astrologer" to "ஜோதிடராக இணையுங்கள்",
        "name" to "முழு பெயர்",
        "phone_number" to "தொலைபேசி எண்",
        "email_address" to "மின்னஞ்சல் முகவரி",
        "experience_years" to "அனுபவம் (ஆண்டுகள்)",
        "skills_expert" to "திறன்கள் (உதாரணம்: வேத, டாரோட்)",
        "price_per_min" to "நிமிடத்திற்கு கட்டணம்",
        "about_you" to "உங்களைப் பற்றி",
        "register_now" to "பதிவு செய்க",
        "premium_consultation" to "பிரீமியம் ஆலோசனை",
        "vedic_remedies" to "வேத பரிகாரங்கள்",
        "gemstone_guide" to "ரத்தின வழிகாட்டி",
        "horoscope" to "ராசி பலன்",
        "live_astrologer" to "நேரடி ஜோதிடர்",
        "daily_horoscope" to "தினசரி ராசி பலன்",
        "chat_services" to "சாட் சேவை",
        "video_call" to "வீடியோ அழைப்பு",
        "audio_call" to "ஆடியோ அழைப்பு",
        "view_all" to "அனைத்தையும் பார்க்க",
        "loading" to "ஏற்றுகிறது...",
        "aries" to "மேஷம்",
        "taurus" to "ரிஷபம்",
        "gemini" to "மிதுனம்",
        "cancer" to "கடகம்",
        "leo" to "சிம்மம்",
        "virgo" to "கன்னி",
        "libra" to "துலாம்",
        "scorpio" to "விருச்சிகம்",
        "sagittarius" to "தனுசு",
        "capricorn" to "மகரம்",
        "aquarius" to "கும்பம்",
        "pisces" to "மீனம்",
        "all" to "அனைத்தும்",
        "love" to "காதல்",
        "career" to "வேலைவாய்ப்பு",
        "finance" to "நிதி",
        "marriage" to "திருமணம்",
        "health" to "உடல்நலம்",
        "education" to "கல்வி",
        "element" to "தத்துவம்",
        "lord" to "அதிபதி",
        "category" to "வகை",
        "daily_prediction" to "இன்றைய பலன்",
        "ok" to "சரி",
        "real_name" to "உண்மைப் பெயர் *",
        "display_name" to "தோற்றப் பெயர் (செயலிக்காக)",
        "gender" to "பாலினம்",
        "male" to "ஆண்",
        "female" to "பெண்",
        "other" to "மற்றவை",
        "dob" to "பிறந்த தேதி",
        "tob" to "பிறந்த நேரம்",
        "pob" to "பிறந்த இடம்",
        "cell_no_1" to "செல்பேசி எண் 1 *",
        "cell_no_2" to "செல்பேசி எண் 2",
        "whatsapp_no" to "வாட்ஸ்அப் எண்",
        "address" to "முழு முகவரி",
        "aadhar_no" to "ஆதார் எண்",
        "pan_no" to "பான் எண்",
        "profession" to "தொழில் (வேத, டாரோட் போன்றவை)",
        "bank_details" to "வங்கி விவரங்கள் (கணக்கு எண் / IFSC)",
        "upi_name" to "UPI பெயர்",
        "upi_number" to "UPI எண்",
        "submit_registration" to "பதிவை சமர்ப்பிக்கவும்",
        "personal_details" to "தனிப்பட்ட விவரங்கள்",
        "birth_details" to "பிறப்பு விவரங்கள்",
        "contact_info" to "தொடர்பு விவரங்கள்",
        "professional_info" to "தொழில்முறை விவரங்கள்",
        "payment_details" to "கட்டண விவரங்கள்",
        "consultation_history" to "ஆலோசனை வரலாறு",
        "unlimited_horoscope" to "வரம்பற்ற ஜாதகம் (40 நிமிடம்)",
        "unlimited_horoscope_desc" to "காதல், வேலை, ஆரோக்கியம், செல்வம் மற்றும் பலவற்றில் ஆழமான வழிகாட்டுதலைப் பெறுங்கள்.",
        "chat" to "சாட்",
        "video" to "வீடியோ",
        "call" to "அழைப்பு",
        "joined_queue" to "வரிசையில் இணைந்தீர்கள்! உங்களுக்கு அறிவிக்கப்படும்.",
        "failed_join_queue" to "வரிசையில் இணைய முடியவில்லை",
        "low_balance_title" to "குறைந்த இருப்பு!",
        "low_balance_desc" to "போதிய நிதி இல்லாததால் தற்போதைய அமர்வு முடிவடைந்தது. தொடர ரீசார்ஜ் செய்யவும்.",
        "add_funds_now" to "நிதி சேர்க்கவும்",
        "later" to "பிறகு செய்கிறேன்",
        "emergency_banner_title" to "அவசர சேவைக்கு தயார்!",
        "emergency_banner_desc" to "அவசர அமர்வுகள் மூலம் உங்கள் வருமானத்தை அதிகரிக்கவும்.",
        "total_earnings" to "மொத்த வருமானம்",
        "withdraw" to "பணத்தை எடுக்க",
        "min_withdrawal_desc" to "குறைந்தபட்சம் ₹500 தேவை",
        "withdrawal_request_success" to "பணத்தை எடுக்கும் கோரிக்கை வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது",
        "withdrawal_history_title" to "சமீபத்திய பணப் பரிமாற்ற நிலை",
        "today_progress" to "இன்றைய முன்னேற்றம்",
        "service_availability" to "சேவை கிடைக்கும் நிலை",
        "customers_waiting" to "வாடிக்கையாளர்கள் காத்திருக்கிறார்கள்",
        "process_current_session" to "அடுத்த நபருடன் இணைய தற்போதைய அமர்வை முடிக்கவும்.",
        "earnings" to "வருமானம்",
        "history" to "வரலாறு",
        "unlimited_session" to "அமர்வு",
        "press_back_again_to_end" to "அழைப்பை முடிக்க மீண்டும் பின்னால் செல்லவும்",
        "muted" to "ஒலி முடக்கப்பட்டது",
        "unmuted" to "ஒலி இயக்கப்பட்டது",
        "camera_on" to "கேமரா ஆன்",
        "camera_off" to "கேமரா ஆஃப்",
        "speaker_on" to "ஸ்பீக்கர் ஆன்",
        "speaker_off" to "ஸ்பீக்கர் ஆஃப்",
        "waiting_client_data" to "வாடிக்கையாளர் விவரங்களுக்காக காத்திருக்கிறது...",
        "details_updated" to "விவரங்கள் புதுப்பிக்கப்பட்டன",
        "failed_calculate_match" to "பொருத்தம் கணக்கிட முடியவில்லை",
        "error_calculate_match" to "பொருத்தம் கணக்கிடுவதில் பிழை",
        "recording_started" to "பதிவு தொடங்கப்பட்டது",
        "recording_failed" to "பதிவு செய்ய முடியவில்லை",
        "recording_synced" to "பதிவு மேகக்கணியில் சேமிக்கப்பட்டது",
        "review_dialog_title" to "உங்கள் அமர்வு எப்படி இருந்தது?",
        "review_placeholder" to "உங்கள் அனுபவத்தைப் பகிரவும் (விருப்பத்தேர்வு)",
        "submit_review" to "கருத்தைச் சமர்ப்பிக்கவும்",
        "skip" to "தவிர்க்கவும்",
        "review_submitted" to "கருத்து சமர்ப்பிக்கப்பட்டது!",
        "communication_established" to "தொடர்பு ஏற்படுத்தப்பட்டது",
        "consultation_started" to "ஆலோசனை தொடங்கியது",
        "view_rasi_chart" to "ஜாதகத்தைப் பார்க்க",
        "client_rasi_chart" to "வாடிக்கையாளர் ராசி கட்டம்",
        "partner_rasi_chart" to "துணைவர் ராசி கட்டம்",
        "marriage_compatibility" to "திருமணப் பொருத்தப் பலன்"
    )

    fun get(key: String, isTamil: Boolean): String {
        return if (isTamil) {
            tamil[key] ?: english[key] ?: key
        } else {
            english[key] ?: key
        }
    }
}
