package com.astro5star.app.utils

object Localization {
    // English Strings
    private val english = mapOf(
        "home_title" to "Astro 5 Star",
        "home" to "Home",
        "profile" to "Profile",
        "settings" to "Settings",
        "logout" to "Logout",
        "join_as_astrologer" to "Join as Astrologer",
        "name" to "Full Name",
        "phone_number" to "Phone Number",
        "email_address" to "Email Address",
        "experience_years" to "Experience (Years)",
        "skills_expert" to "Skills (e.g. Vedic, Tarot)",
        "price_per_min" to "Price Per Min",
        "about_you" to "About You",
        "register_now" to "Register Now",
        "premium_consultation" to "Premium Consultation",
        "vedic_remedies" to "Vedic Remedies",
        "gemstone_guide" to "Gemstone Guide",
        "horoscope" to "Horoscope",
        "daily_horoscope" to "Daily Horoscope",
        "chat_services" to "Chat Services",
        "video_call" to "Video Call",
        "audio_call" to "Audio Call",
        "view_all" to "View All",
        "loading" to "Loading...",
        "aries" to "Aries",
        "taurus" to "Taurus",
        "gemini" to "Gemini",
        "cancer" to "Cancer",
        "leo" to "Leo",
        "virgo" to "Virgo",
        "libra" to "Libra",
        "scorpio" to "Scorpio",
        "sagittarius" to "Sagittarius",
        "capricorn" to "Capricorn",
        "aquarius" to "Aquarius",
        "pisces" to "Pisces",
        "all" to "All",
        "love" to "Love",
        "career" to "Career",
        "finance" to "Finance",
        "marriage" to "Marriage",
        "health" to "Health",
        "education" to "Education",
        "element" to "Element",
        "lord" to "Lord",
        "category" to "Category",
        "daily_prediction" to "Daily Prediction",
        "ok" to "OK",
        "real_name" to "Real Name *",
        "display_name" to "Display Name (For App)",
        "gender" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "other" to "Other",
        "dob" to "Date of Birth",
        "tob" to "Time of Birth",
        "pob" to "Place of Birth",
        "cell_no_1" to "Cell Number 1 *",
        "cell_no_2" to "Cell Number 2",
        "whatsapp_no" to "WhatsApp Number",
        "address" to "Full Address",
        "aadhar_no" to "Aadhar Number",
        "pan_no" to "PAN Number",
        "profession" to "Profession (e.g. Vedic, Tarot)",
        "bank_details" to "Bank Details (Acct No / IFSC)",
        "upi_name" to "UPI Name",
        "upi_number" to "UPI Number",
        "submit_registration" to "Submit Registration",
        "personal_details" to "Personal Details",
        "birth_details" to "Birth Details",
        "contact_info" to "Contact Info",
        "professional_info" to "Professional Info",
        "payment_details" to "Payment Details"
    )

    // Tamil Strings
    private val tamil = mapOf(
        "home_title" to "ஆஸ்ட்ரோ 5 ஸ்டார்",
        "home" to "முகப்பு",
        "profile" to "சுயவிவரம்",
        "settings" to "அமைப்புகள்",
        "logout" to "வெளியேறு",
        "join_as_astrologer" to "ஜோதிடராக இணையுங்கள்",
        "name" to "முழு பெயர்",
        "phone_number" to "தொலைபேசி எண்",
        "email_address" to "மின்னஞ்சல் முகவரி",
        "experience_years" to "அனுபவம் (ஆண்டுகள்)",
        "skills_expert" to "திறன்கள் (உதாரணம்: வேத, டாரோட்)",
        "price_per_min" to "நிமிடத்திற்கு கட்டணம்",
        "about_you" to "உங்களைப் பற்றி",
        "register_now" to "பதிவு செய்க",
        "premium_consultation" to "பிரீமியம் ஆலோசனை",
        "vedic_remedies" to "வேத பரிகாரங்கள்",
        "gemstone_guide" to "ரத்தின வழிகாட்டி",
        "horoscope" to "ராசி பலன்",
        "daily_horoscope" to "தினசரி ராசி பலன்",
        "chat_services" to "சாட் சேவை",
        "video_call" to "வீடியோ அழைப்பு",
        "audio_call" to "ஆடியோ அழைப்பு",
        "view_all" to "அனைத்தையும் பார்க்க",
        "loading" to "ஏற்றுகிறது...",
        "aries" to "மேஷம்",
        "taurus" to "ரிஷபம்",
        "gemini" to "மிதுனம்",
        "cancer" to "கடகம்",
        "leo" to "சிம்மம்",
        "virgo" to "கன்னி",
        "libra" to "துலாம்",
        "scorpio" to "விருச்சிகம்",
        "sagittarius" to "தனுசு",
        "capricorn" to "மகரம்",
        "aquarius" to "கும்பம்",
        "pisces" to "மீனம்",
        "all" to "அனைத்தும்",
        "love" to "காதல்",
        "career" to "வேலைவாய்ப்பு",
        "finance" to "நிதி",
        "marriage" to "திருமணம்",
        "health" to "உடல்நலம்",
        "education" to "கல்வி",
        "element" to "தத்துவம்",
        "lord" to "அதிபதி",
        "category" to "வகை",
        "daily_prediction" to "இன்றைய பலன்",
        "ok" to "சரி",
        "real_name" to "உண்மைப் பெயர் *",
        "display_name" to "தோற்றப் பெயர் (செயலிக்காக)",
        "gender" to "பாலினம்",
        "male" to "ஆண்",
        "female" to "பெண்",
        "other" to "மற்றவை",
        "dob" to "பிறந்த தேதி",
        "tob" to "பிறந்த நேரம்",
        "pob" to "பிறந்த இடம்",
        "cell_no_1" to "செல்பேசி எண் 1 *",
        "cell_no_2" to "செல்பேசி எண் 2",
        "whatsapp_no" to "வாட்ஸ்அப் எண்",
        "address" to "முழு முகவரி",
        "aadhar_no" to "ஆதார் எண்",
        "pan_no" to "பான் எண்",
        "profession" to "தொழில் (வேத, டாரோட் போன்றவை)",
        "bank_details" to "வங்கி விவரங்கள் (கணக்கு எண் / IFSC)",
        "upi_name" to "UPI பெயர்",
        "upi_number" to "UPI எண்",
        "submit_registration" to "பதிவை சமர்ப்பிக்கவும்",
        "personal_details" to "தனிப்பட்ட விவரங்கள்",
        "birth_details" to "பிறப்பு விவரங்கள்",
        "contact_info" to "தொடர்பு விவரங்கள்",
        "professional_info" to "தொழில்முறை விவரங்கள்",
        "payment_details" to "கட்டண விவரங்கள்"
    )

    fun get(key: String, isTamil: Boolean): String {
        return if (isTamil) {
            tamil[key] ?: english[key] ?: key
        } else {
            english[key] ?: key
        }
    }
}
